name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TF_CLI_ARGS: '-input=false'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform init
        run: terraform init
        working-directory: terraform
      - name: Terraform plan
        if: github.event_name == 'pull_request'
        run: terraform plan
        working-directory: terraform
      - name: Terraform plan
        if: github.event_name == 'pull_request'
        run: terraform plan
        working-directory: terraform
        env:
          TF_LOG: DEBUG
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: terraform
